version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: marinhodiscos-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: marinhodiscos
      POSTGRES_USER: marinho
      POSTGRES_PASSWORD: golnau789
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marinho -d marinhodiscos"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
